### ISSUE TITLE
Providing a note Digital Ocean is currently broken

### ISSUE THREAD

**Issue by elantrix** [puphpet/puphpet#1252]
The Digital ocean provider support would be a very popular option and a lot of people would be very confused with the sudden disappearance.

I agree that the option should be removed, but having the plugin so close to being fixed, it's probably a good idea to at least put a note in the blue alert box stating that the DO ocean is currently broken out of puphpet's control and should be back soon.

At least that will reduce the unintended stress to some of those who rely on it.

**Comment by markushausammann** [comment]
@jtreminio what does that mean?

**Comment by jtreminio** [comment]
@markushausammann I mean I haven't received any news. The ticket is open in the plugin's repo. As soon as it works DO will be re-enabled. Other than that happening, I can't do anything at all.

**Comment by markushausammann** [comment]
Ok, I understand, gave a +1 to the issue in the plugin repo. I guess that's all anyone here can do.

**Comment by pkalisz** [comment]
They've already figured out the problem. Lets hope it will be fixed asap :)

**Comment by pkalisz** [comment]
@jtreminio , it looks it is fixed. When do expect to bring DO back to puphpet.com?

**Comment by jtreminio** [comment]
@pkalisz it is not yet fixed as a PR has not been merged.

https://github.com/smdahlen/vagrant-digitalocean/pull/172

**Comment by orthes** [comment]
@jtreminio It looks like https://github.com/smdahlen/vagrant-digitalocean/pull/172 was finally merged in v0.7.2

**Comment by kusmierz** [comment]
+1

**Comment by rlweb** [comment]
Could we add Digital Ocean back to the website?

**Comment by markushausammann** [comment]
Yes, please.

**Comment by jtreminio** [comment]
Will be re-adding shortly.
