### ISSUE TITLE
Python pip fails

### ISSUE THREAD

**Issue by shivapoudel** [puphpet/puphpet#1518]
@jtreminio I am using Debian wheezy 7.5 x64 box and python configuration is:

```yaml
python:
    install: '1'
    packages:
        - transifex-client
    versions:
        73LhG9IauJx6:
            version: 3.4.0
            virtualenv: '1'
```

I am getting this error

```shell
==> default: Notice: /Stage[main]/Puphpet::Python::Pip/Package[python-setuptools]/ensure: ensure cha
nged 'purged' to 'present'
==> default: Error: Could not set 'present' on ensure: Could not locate the pip command. at 32:/tmp/
vagrant-puppet-3/manifests/nodes/python.pp
==> default: Error: Could not set 'present' on ensure: Could not locate the pip command. at 32:/tmp/
vagrant-puppet-3/manifests/nodes/python.pp
==> default: Wrapped exception:
==> default: Could not locate the pip command.
==> default: Error: /Stage[main]/Main/Package[transifex-client]/ensure: change from absent to presen
t failed: Could not set 'present' on ensure: Could not locate the pip command. at 32:/tmp/vagrant-pu
ppet-3/manifests/nodes/python.pp
```

**Comment by shivapoudel** [comment]
I am trying to install `transifex-client`
This issue is on first `vagrant up` and after `vagrant provision` issue is gone, don't know why :)

**Comment by jtreminio** [comment]
Fixed by 1932017

**Comment by mrconnerton** [comment]
I am still getting the "Could not locate the pip command" with a fresh config.
https://gist.github.com/mrconnerton/e5f11b63205f41f6cc25

**Comment by mrconnerton** [comment]
==> default: Error: Could not set 'present' on ensure: Could not locate the pip command. at 6:/tmp/vagrant-puppet/modules-2939176192d947b60efa0e4c6ee80899/supervisord/manifests/install.pp
==> default: Error: Could not set 'present' on ensure: Could not locate the pip command. at 6:/tmp/vagrant-puppet/modules-2939176192d947b60efa0e4c6ee80899/supervisord/manifests/install.pp
==> default: Wrapped exception:
==> default: Could not locate the pip command.
==> default: Error: /Stage[main]/Supervisord::Install/Package[supervisor]/ensure: change from absent to present failed: Could not set 'present' on ensure: Could not locate the pip command. at 6:/tmp/vagrant-puppet/modules-2939176192d947b60efa0e4c6ee80899/supervisord/manifests/install.pp
