### ISSUE TITLE
stdin: is not a tty... again and again

### ISSUE THREAD

**Issue by numediaweb** [puphpet/puphpet#1922]
I know that that this error is "harmless" bu still, it is annoying especially if you want to share the project with other devs.

Is there any possible fix for this error in windows?

 ```
==> default: Mounting shared folders...
    default: /var/www => C:/apps/ek3-abdel
    default: /vagrant => C:/apps/ek3-abdel
    default: /tmp/vagrant-puppet/modules-12b781c1145e733a35045d653167410b => C:/apps/ek3-abdel/puphpet/puppet/modules
    default: /tmp/vagrant-puppet/manifests-893fcda21077f5a583c2dbbba8515c0a => C:/apps/ek3-abdel/puphpet/puppet
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: C:/Users/Aidrissi/AppData/Local/Temp/vagrant-shell20150929-8828-p80si6.sh
==> default: stdin: is not a tty
==> default:
==> default:  ____        ____  _   _ ____      _      generated using
==> default: |  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
==> default: | |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
==> default: |  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
==> default: |_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|
==> default: Running initial-setup apt-get update

```

**Comment by akomm** [comment]
Which Guest-OS did you pick?

**Comment by numediaweb** [comment]
I'm using windows and I fixed it by modifying this file `myapp\puphpet\vagrant\Vagrantfile-local`, I added the following "fix-no-tty" 4 lines
```
...
      virtualbox.customize ['setextradata', :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//vagrant", '1']

      data['vm']['synced_folder'].each do |i, folder|
        virtualbox.customize ['setextradata', :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//#{i}", '1']
      end
    end
	
	config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
	end
	
  end
...
```

**Comment by fnagel** [comment]
I'm having one of these lines on every `vagrant up` on Windows 8.1 with Debian guest host only. No "errors" when using Ubuntu. Hope that helps.

**Comment by jtreminio** [comment]
Fixed in latest boxes.

**Comment by vincenzo** [comment]
@jtreminio Still happens once at the beginning of a provision. 

```
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/vincenzo/vagrant/solas.psh
    default: /tmp/vagrant-puppet/modules-133be20d78918bc00a2511665383c540 => /Users/vincenzo/vagrant/solas.psh/puphpet/puppet/modules
    default: /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812 => /Users/vincenzo/vagrant/solas.psh/puphpet/puppet/manifests
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: /var/folders/x2/8b74vbnx6fz86zyxzp662v2h0000gp/T/vagrant-shell20160116-13588-1f7hhgo.sh
==> default: 
==> default:  ____        ____  _   _ ____      _      generated using
==> default: |  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
==> default: | |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
==> default: |  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
==> default: |_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|
==> default: 
```

Using latest wheezy box here.
