### ISSUE TITLE
/tmp/vagrant-shell: line 34: /opt/puppetlabs/puppet/bin/gem: No such file or directory

### ISSUE THREAD

**Issue by diegocaprioli** [puphpet/puphpet#2065]
I'm getting this error on a brand new `vagrant up`:

```
==> default: /tmp/vagrant-shell: line 34: /opt/puppetlabs/puppet/bin/gem: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

My config file:

```
vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x64
        box_url: puphpet/ubuntu1404-x64
        hostname: local.puphpet
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_r4atkyd3b8xj:
                    host: '7816'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: 'on'
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
        synced_folder:
            vflsf_kik0kpgip2mu:
                source: ./shared
                target: /var/www
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
        insert_key: false
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
users_groups:
    install: '1'
    groups: {  }
    users: {  }
locale:
    install: '1'
    settings:
        default_locale: ''
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
firewall:
    install: '1'
    rules: {  }
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        nxv_axblfc4iyx4z:
            server_name: dianca.app
            www_root: /var/www/dianca
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 1m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_xdkkz2u5v2z1:
                    location: /
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: ''
                    proxy_redirect: ''
                nxvl_eb6b6zpq03e1:
                    location: '~ \.php$'
                    autoindex: 'off'
                    internal: 'false'
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
                    set:
                        - '$path_info $fastcgi_path_info'
                    proxy: ''
                    proxy_redirect: ''
    proxies: {  }
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_2729q0k0xhlc:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_cxwzvfb66142:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_fyjbhpzuy2f2:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mysql
            - mbstring
            - mcrypt
            - curl
            - xsl
            - gd
            - imagick
        pear:
            - SOAP
            - PHP_Debug
        pecl:
            - PDO_MYSQL
            - intl
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_ypqwcc1xq46u:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        rv_r70tnm34gco3:
            default: '1'
            bundler: '1'
            version: 1.9.3
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '0'
    settings:
        version: '5'
    npm_packages: {  }
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: 'On'
        error_reporting: '-1'
        date.timezone: UTC
mariadb:
    install: '1'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mariadbnu_rfc5fbz0qbdq:
            name: dbuser
            password: '123'
    databases:
        mariadbnd_8gq4rf787mc1:
            name: dbname
            sql: ''
    grants:
        mariadbng_z483ntwfd9j3:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: 0
    settings:
        version: '5.5'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_2yf6vlspyd65:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_7tdvxyo3unjk:
            name: dbname
            sql: ''
    grants:
        mysqlng_cbw273mxzdke:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.4'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '0'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 2.6.0
    databases: {  }
redis:
    install: '0'
    settings:
        conf_port: '6379'
sqlite:
    install: '0'
    adminer: 0
    databases: {  }
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 2.1.0
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'
```

The full vagrant up std output is this:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'puphpet/ubuntu1404-x64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> default: A newer version of the box 'puphpet/ubuntu1404-x64' is available! You currently
==> default: have version '1.2'. The latest is version '20151201'. Run
==> default: `vagrant box update` to update.
==> default: Setting the name of the VM: magento-test_default_1451225196910_51125
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 7816 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.10
    default: VirtualBox Version: 5.0
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /var/www => /home/diego/Work/Dianca/VMs/magento-test/shared
    default: /vagrant => /home/diego/Work/Dianca/VMs/magento-test
    default: /tmp/vagrant-puppet/modules-01ebe7071b7890dd3bcd23e64bea4ca4 => /home/diego/Work/Dianca/VMs/magento-test/puphpet/puppet/modules
    default: /tmp/vagrant-puppet/manifests-75f35e3bc7e32744860c4bb229c88812 => /home/diego/Work/Dianca/VMs/magento-test/puphpet/puppet/manifests
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20151227-26082-c3kfbm.sh
==> default: stdin: is not a tty
==> default: 
==> default:  ____        ____  _   _ ____      _      generated using
==> default: |  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
==> default: | |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
==> default: |  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
==> default: |_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|
==> default: Ign http://us.archive.ubuntu.com trusty InRelease
==> default: Get:1 http://security.ubuntu.com trusty-security InRelease [64.4 kB]
==> default: Get:2 http://us.archive.ubuntu.com trusty-updates InRelease [64.4 kB]
==> default: Get:3 http://us.archive.ubuntu.com trusty-backports InRelease [64.5 kB]
==> default: Get:4 http://security.ubuntu.com trusty-security/main Sources [101 kB]
==> default: Hit http://us.archive.ubuntu.com trusty Release.gpg
==> default: Get:5 http://us.archive.ubuntu.com trusty-updates/main Sources [246 kB]
==> default: Get:6 http://security.ubuntu.com trusty-security/restricted Sources [4,035 B]
==> default: Get:7 http://security.ubuntu.com trusty-security/universe Sources [31.9 kB]
==> default: Get:8 http://security.ubuntu.com trusty-security/multiverse Sources [2,353 B]
==> default: Get:9 http://security.ubuntu.com trusty-security/main amd64 Packages [396 kB]
==> default: Get:10 http://us.archive.ubuntu.com trusty-updates/restricted Sources [5,359 B]
==> default: Get:11 http://us.archive.ubuntu.com trusty-updates/universe Sources [145 kB]
==> default: Get:12 http://us.archive.ubuntu.com trusty-updates/multiverse Sources [5,167 B]
==> default: Get:13 http://us.archive.ubuntu.com trusty-updates/main amd64 Packages [678 kB]
==> default: Get:14 http://security.ubuntu.com trusty-security/restricted amd64 Packages [13.0 kB]
==> default: Get:15 http://us.archive.ubuntu.com trusty-updates/restricted amd64 Packages [15.9 kB]
==> default: Get:16 http://security.ubuntu.com trusty-security/universe amd64 Packages [122 kB]
==> default: Get:17 http://us.archive.ubuntu.com trusty-updates/universe amd64 Packages [332 kB]
==> default: Get:18 http://us.archive.ubuntu.com trusty-updates/multiverse amd64 Packages [13.0 kB]
==> default: Get:19 http://us.archive.ubuntu.com trusty-updates/main i386 Packages [654 kB]
==> default: Get:20 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [4,795 B]
==> default: Get:21 http://security.ubuntu.com trusty-security/main i386 Packages [374 kB]
==> default: Get:22 http://us.archive.ubuntu.com trusty-updates/restricted i386 Packages [15.6 kB]
==> default: Get:23 http://us.archive.ubuntu.com trusty-updates/universe i386 Packages [334 kB]
==> default: Get:24 http://us.archive.ubuntu.com trusty-updates/multiverse i386 Packages [13.2 kB]
==> default: Get:25 http://us.archive.ubuntu.com trusty-updates/main Translation-en [340 kB]
==> default: Get:26 http://us.archive.ubuntu.com trusty-updates/multiverse Translation-en [6,832 B]
==> default: Get:27 http://us.archive.ubuntu.com trusty-updates/restricted Translation-en [3,699 B]
==> default: Get:28 http://us.archive.ubuntu.com trusty-updates/universe Translation-en [174 kB]
==> default: Get:29 http://us.archive.ubuntu.com trusty-backports/main Sources [8,221 B]
==> default: Get:30 http://us.archive.ubuntu.com trusty-backports/restricted Sources [28 B]
==> default: Get:31 http://us.archive.ubuntu.com trusty-backports/universe Sources [33.2 kB]
==> default: Get:32 http://us.archive.ubuntu.com trusty-backports/multiverse Sources [1,898 B]
==> default: Get:33 http://us.archive.ubuntu.com trusty-backports/main amd64 Packages [9,402 B]
==> default: Get:34 http://us.archive.ubuntu.com trusty-backports/restricted amd64 Packages [28 B]
==> default: Get:35 http://us.archive.ubuntu.com trusty-backports/universe amd64 Packages [39.6 kB]
==> default: Get:36 http://us.archive.ubuntu.com trusty-backports/multiverse amd64 Packages [1,571 B]
==> default: Get:37 http://security.ubuntu.com trusty-security/restricted i386 Packages [12.7 kB]
==> default: Get:38 http://us.archive.ubuntu.com trusty-backports/main i386 Packages [9,411 B]
==> default: Get:39 http://us.archive.ubuntu.com trusty-backports/restricted i386 Packages [28 B]
==> default: Get:40 http://security.ubuntu.com trusty-security/universe i386 Packages [122 kB]
==> default: Get:41 http://us.archive.ubuntu.com trusty-backports/universe i386 Packages [39.6 kB]
==> default: Get:42 http://us.archive.ubuntu.com trusty-backports/multiverse i386 Packages [1,552 B]
==> default: Get:43 http://us.archive.ubuntu.com trusty-backports/main Translation-en [5,549 B]
==> default: Get:44 http://us.archive.ubuntu.com trusty-backports/multiverse Translation-en [1,215 B]
==> default: Get:45 http://us.archive.ubuntu.com trusty-backports/restricted Translation-en [14 B]
==> default: Get:46 http://us.archive.ubuntu.com trusty-backports/universe Translation-en [34.5 kB]
==> default: Get:47 http://security.ubuntu.com trusty-security/multiverse i386 Packages [4,972 B]
==> default: Get:48 http://security.ubuntu.com trusty-security/main Translation-en [218 kB]
==> default: Hit http://us.archive.ubuntu.com trusty Release
==> default: Hit http://us.archive.ubuntu.com trusty/main Sources
==> default: Hit http://us.archive.ubuntu.com trusty/restricted Sources
==> default: Hit http://us.archive.ubuntu.com trusty/universe Sources
==> default: Hit http://us.archive.ubuntu.com trusty/multiverse Sources
==> default: Hit http://us.archive.ubuntu.com trusty/main amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty/restricted amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty/universe amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty/multiverse amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty/main i386 Packages
==> default: Hit http://us.archive.ubuntu.com trusty/restricted i386 Packages
==> default: Get:49 http://security.ubuntu.com trusty-security/multiverse Translation-en [2,437 B]
==> default: Hit http://us.archive.ubuntu.com trusty/universe i386 Packages
==> default: Get:50 http://security.ubuntu.com trusty-security/restricted Translation-en [3,206 B]
==> default: Hit http://us.archive.ubuntu.com trusty/multiverse i386 Packages
==> default: Get:51 http://security.ubuntu.com trusty-security/universe Translation-en [71.1 kB]
==> default: Hit http://us.archive.ubuntu.com trusty/main Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty/multiverse Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty/restricted Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty/universe Translation-en
==> default: Ign http://us.archive.ubuntu.com trusty/main Translation-en_US
==> default: Ign http://us.archive.ubuntu.com trusty/multiverse Translation-en_US
==> default: Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US
==> default: Ign http://us.archive.ubuntu.com trusty/universe Translation-en_US
==> default: Fetched 4,845 kB in 22s (217 kB/s)
==> default: Reading package lists...
==> default: Installing Anacron
==> default: Ign http://us.archive.ubuntu.com trusty InRelease
==> default: Hit http://security.ubuntu.com trusty-security InRelease
==> default: Hit http://us.archive.ubuntu.com trusty-updates InRelease
==> default: Hit http://us.archive.ubuntu.com trusty-backports InRelease
==> default: Hit http://security.ubuntu.com trusty-security/main Sources
==> default: Hit http://us.archive.ubuntu.com trusty Release.gpg
==> default: Hit http://security.ubuntu.com trusty-security/restricted Sources
==> default: Hit http://us.archive.ubuntu.com trusty-updates/main Sources
==> default: Hit http://us.archive.ubuntu.com trusty-updates/restricted Sources
==> default: Hit http://security.ubuntu.com trusty-security/universe Sources
==> default: Hit http://us.archive.ubuntu.com trusty-updates/universe Sources
==> default: Hit http://security.ubuntu.com trusty-security/multiverse Sources
==> default: Hit http://us.archive.ubuntu.com trusty-updates/multiverse Sources
==> default: Hit http://security.ubuntu.com trusty-security/main amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-updates/main amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-updates/restricted amd64 Packages
==> default: Hit http://security.ubuntu.com trusty-security/restricted amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-updates/universe amd64 Packages
==> default: Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-updates/multiverse amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-updates/main i386 Packages
==> default: Hit http://security.ubuntu.com trusty-security/multiverse amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-updates/restricted i386 Packages
==> default: Hit http://security.ubuntu.com trusty-security/main i386 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-updates/universe i386 Packages
==> default: Hit http://security.ubuntu.com trusty-security/restricted i386 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-updates/multiverse i386 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-updates/main Translation-en
==> default: Hit http://security.ubuntu.com trusty-security/universe i386 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-updates/multiverse Translation-en
==> default: Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages
==> default: Hit http://security.ubuntu.com trusty-security/main Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty-updates/restricted Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty-updates/universe Translation-en
==> default: Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty-backports/main Sources
==> default: Hit http://security.ubuntu.com trusty-security/restricted Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty-backports/restricted Sources
==> default: Hit http://us.archive.ubuntu.com trusty-backports/universe Sources
==> default: Hit http://security.ubuntu.com trusty-security/universe Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty-backports/multiverse Sources
==> default: Hit http://us.archive.ubuntu.com trusty-backports/main amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-backports/restricted amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-backports/universe amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-backports/multiverse amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-backports/main i386 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-backports/restricted i386 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-backports/universe i386 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-backports/multiverse i386 Packages
==> default: Hit http://us.archive.ubuntu.com trusty-backports/main Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty-backports/multiverse Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty-backports/restricted Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty-backports/universe Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty Release
==> default: Hit http://us.archive.ubuntu.com trusty/main Sources
==> default: Hit http://us.archive.ubuntu.com trusty/restricted Sources
==> default: Hit http://us.archive.ubuntu.com trusty/universe Sources
==> default: Hit http://us.archive.ubuntu.com trusty/multiverse Sources
==> default: Hit http://us.archive.ubuntu.com trusty/main amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty/restricted amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty/universe amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty/multiverse amd64 Packages
==> default: Hit http://us.archive.ubuntu.com trusty/main i386 Packages
==> default: Hit http://us.archive.ubuntu.com trusty/restricted i386 Packages
==> default: Hit http://us.archive.ubuntu.com trusty/universe i386 Packages
==> default: Hit http://us.archive.ubuntu.com trusty/multiverse i386 Packages
==> default: Hit http://us.archive.ubuntu.com trusty/main Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty/multiverse Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty/restricted Translation-en
==> default: Hit http://us.archive.ubuntu.com trusty/universe Translation-en
==> default: Ign http://us.archive.ubuntu.com trusty/main Translation-en_US
==> default: Ign http://us.archive.ubuntu.com trusty/multiverse Translation-en_US
==> default: Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US
==> default: Ign http://us.archive.ubuntu.com trusty/universe Translation-en_US
==> default: Reading package lists...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: Suggested packages:
==> default:   default-mta mail-transport-agent
==> default: The following NEW packages will be installed:
==> default:   anacron
==> default: 0 upgraded, 1 newly installed, 0 to remove and 222 not upgraded.
==> default: Need to get 26.2 kB of archives.
==> default: After this operation, 182 kB of additional disk space will be used.
==> default: Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty/main anacron amd64 2.3-20ubuntu1 [26.2 kB]
==> default: Fetched 26.2 kB in 0s (43.3 kB/s)
==> default: Selecting previously unselected package anacron.
==> default: (Reading database ... 63532 files and directories currently installed.)
==> default: Preparing to unpack .../anacron_2.3-20ubuntu1_amd64.deb ...
==> default: Unpacking anacron (2.3-20ubuntu1) ...
==> default: Processing triggers for man-db (2.6.7.1-1) ...
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: ureadahead will be reprofiled on next reboot
==> default: Setting up anacron (2.3-20ubuntu1) ...
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: Finished installing Anacron
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following NEW packages will be installed:
==> default:   iptables-persistent
==> default: 0 upgraded, 1 newly installed, 0 to remove and 222 not upgraded.
==> default: Need to get 10.2 kB of archives.
==> default: After this operation, 62.5 kB of additional disk space will be used.
==> default: Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty/universe iptables-persistent all 0.5.7 [10.2 kB]
==> default: Preconfiguring packages ...
==> default: Fetched 10.2 kB in 0s (25.6 kB/s)
==> default: Selecting previously unselected package iptables-persistent.
==> default: (Reading database ... 63554 files and directories currently installed.)
==> default: Preparing to unpack .../iptables-persistent_0.5.7_all.deb ...
==> default:  Removing any system startup links for /etc/init.d/iptables-persistent ...
==> default: Unpacking iptables-persistent (0.5.7) ...
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: Setting up iptables-persistent (0.5.7) ...
==> default:  * Loading iptables rules...
==> default:  *  IPv4...
==> default:  *  IPv6...
==> default:    ...done.
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20151227-26082-capi5x.sh
==> default: stdin: is not a tty
==> default: Generating public/private rsa key pair.
==> default: Your identification has been saved in /vagrant/puphpet/files/dot/ssh/root_id_rsa.
==> default: Your public key has been saved in /vagrant/puphpet/files/dot/ssh/root_id_rsa.pub.
==> default: The key fingerprint is:
==> default: 21:39:a5:e8:3c:40:7f:3d:5c:07:7f:54:f1:fe:c4:0d root@local
==> default: The key's randomart image is:
==> default: +--[ RSA 2048]----+
==> default: |  .     . o.. .oo|
==> default: | . . . * . o .  .|
==> default: |  . o * =   . E .|
==> default: |   + . o o   . +.|
==> default: |    +   S       =|
==> default: |     .         ..|
==> default: |                .|
==> default: |                 |
==> default: |                 |
==> default: +-----------------+
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Your private key for SSH-based authentication has been saved to 'puphpet/files/dot/ssh/root_id_rsa'!
==> default: Generating public/private rsa key pair.
==> default: Your identification has been saved in /vagrant/puphpet/files/dot/ssh/id_rsa.
==> default: Your public key has been saved in /vagrant/puphpet/files/dot/ssh/id_rsa.pub.
==> default: The key fingerprint is:
==> default: 7f:35:8b:82:57:f9:51:eb:92:f8:38:29:b6:53:82:1b root@local
==> default: The key's randomart image is:
==> default: +--[ RSA 2048]----+
==> default: |                 |
==> default: |                 |
==> default: |                .|
==> default: |             . ..|
==> default: |        S   o +. |
==> default: |       E + o.+o+ |
==> default: |        + *.+oo. |
==> default: |       . = =o .  |
==> default: |        ..+...   |
==> default: +-----------------+
==> default: Your private key for SSH-based authentication has been saved to 'puphpet/files/dot/ssh/id_rsa'!
==> default: Adding generated root key to /root/.ssh/id_rsa
==> default: Adding generated root key to /root/.ssh/id_rsa.pub
==> default: Adding generated root key to /root/.ssh/authorized_keys
==> default: Adding generated key to /home/vagrant/.ssh/id_rsa
==> default: Adding generated key to /home/vagrant/.ssh/id_rsa.pub
==> default: Adding generated key to /home/vagrant/.ssh/authorized_keys
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20151227-26082-gzkiqf.sh
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20151227-26082-1odw3us.sh
==> default: stdin: is not a tty
==> default: /tmp/vagrant-shell: line 34: /opt/puppetlabs/puppet/bin/gem: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by diegocaprioli** [comment]
It seems this was an issue related to an old version of my box... It was solved by doing: `vagrant destroy`, `vagrant box update`, and then `vagrant up` again...

**Comment by pySilver** [comment]
this problem still exists on a newly created boxes i think..

**Comment by paolooo** [comment]
Can we reopen this issue? Thanks.

**Comment by gabrielef** [comment]
The solution advised by diegocaprioli solve the issue for me:

> vagrant destroy, vagrant box update, and then vagrant up again...

**Comment by robertgentel** [comment]
> vagrant destroy, vagrant box update, and then vagrant up again...

Not working for me.

**Comment by MlleDelphine** [comment]
Same issue `dpkg-deb: error: '/opt/puphpet-state/puppet5-release-xenial.deb' is not a debian format archive`, `Unable to locate package puppet-agent`, `no valid OpenPGP data found`,  and here with :

- v201812.27.0
- v201812.15.0
- v201808.24.0
- v201807.12.0
- v201806.08.0
- v201803.24.0
- v 201802.02.0

UPDATE : 

I tried with CentOS for now and issue still there.
I was stuck because of `/etc/resolv.conf` nameserver value. 

1. I added 8.8.8.8 
2. Then I manually launch : 
```
      rpm --import https://yum.puppetlabs.com/RPM-GPG-KEY-puppet
        rpm -Uvh "https://yum.puppetlabs.com/puppet5/puppet5-release-el-${RELEASE}.noarch.rpm"
        yum -y install yum-plugin-versionlock puppet-agent-5.3*
        yum versionlock add puppet-agent
    fi

    rm -f /usr/bin/puppet
    ln -s /opt/puppetlabs/bin/puppet /usr/bin/puppet
```
found in `puphpet\shell\install-puppet.sh` line 34 - 44

Still waiting for result...
