### ISSUE TITLE
The drush is not installed in Ubuntu 16.04 on vagrant up or vagrant provision

### ISSUE THREAD

**Issue by cslevy** [puphpet/puphpet#2459]
I got the following error on vagrant up if the drush is set to install

> Error: Execution of '/usr/bin/git checkout --force true' returned 1: error: pathspec 'true' did not match any file(s) known to git.
> ==> machine1: Error: /Stage[main]/Puphpet::Drush::Install/Vcsrepo[/usr/share/drush]/ensure: change from absent to present failed: Execution of '/usr/bin/git checkout --force true' returned 1: error: pathspec 'true' did not match any file(s) known to git.

And 

> Error: /Stage[main]/Puphpet::Drush::Install/Vcsrepo[/usr/share/drush]: Could not evaluate: true is not a local or remote ref 

on vagrant provision

Here is my config yml: https://dpaste.de/4tbV

**Comment by K-4U** [comment]
Same with Ubuntu 14.04. It seems to be a generic drush problem.

Drush DOES get installed, but when executed gives errors about duplicate commands.
Maybe an option to install via composer?

**Comment by CTIGB** [comment]
Same here also with Ubuntu 14.04 - had to provision a new VM the other day and this is a bit of a deal breaker

**Comment by Xenza** [comment]
There appears to be an issue here: /puphpet/puppet/modules/puphpet/manifests/drush/install.pp
$version is evaluation to a boolean so when it is used in vcsrepo it is setting the revision to true rather than the revision set in config.yml.

Changing this section:
`vcsrepo { $drush_location:
      ensure   => present,
      provider => git,
      source   => $drush_github,
      revision => $version,
    } ->`
to
`vcsrepo { $drush_location:
      ensure   => present,
      provider => git,
      source   => $drush_github,
      revision => $drush['version'],
    } ->`
Resolves the issue and makes the drush installation work.

I would submit a pull request for this change but I can't really work out which repository this file is in.

**Comment by therobyouknow** [comment]
also seeing this with 14.04. If I disable drush in the yaml so it is not installed during vagrant up, then the vagrant up runs all way through without error.

So for now, I'm happy to just `sudo apt-get install drush` in a terminal when logged into the VM.

**Comment by Xenza** [comment]
@therobyouknow if you try replacing the section I posted above then you should be able to install the drush version you want via config.yml again.

**Comment by therobyouknow** [comment]
@Xenza Thank you so much - yes - your solution worked: https://github.com/puphpet/puphpet/issues/2459#issuecomment-258617918
I edited that file, then issued command vagrant provision (As I already had a VM running and wanted to use drush)

**Comment by vincenzo** [comment]
Just got the very same issue (with config generated 10 minutes ago), and I fixed it with @Xenza's [suggestion](https://github.com/puphpet/puphpet/issues/2459#issuecomment-258617918). 

@jtreminio Do you think this fix should go in?

**Comment by therobyouknow** [comment]
Original problem still an issue, code solution here already in place so therefore doesn't fix it: https://github.com/puphpet/puphpet/issues/2701
